### PR TITLE
Create jpn.json

### PR DESCRIPTION
**Pull request by adam50200**

### CODE REVIEW

**Comment by adam50200** [comment]
Translation on Japanese. Did I do the right thing?

**Comment by adam50200** [comment]
@getneil ?

**Comment by getneil** [comment]
@adam50200 nope. please read in the README.md the instructions how to contribute on i18n. thanks.

**Comment by adam50200** [comment]
> @adam50200 nope. please read in the README.md the instructions how to contribute on i18n. thanks.

I don’t understand. I've translated the file into Japanese: https://github.com/pkgxdev/ossapp/pull/847/files
I just updated the index file: https://github.com/pkgxdev/ossapp/pull/849/files#diff-8958ad6a4f9c24ec3a32ba90ac0c2bf33af6d1983391c805126e64e0ed49b76aR35

But what's wrong? I don't understand.

**Comment by getneil** [comment]
@adam50200 the file changes have to be in one pull-request not separate. please read the README.md

**Comment by adam50200** [comment]
I don’t can this

**Comment by adam50200** [comment]
😡

**Pull request closed without merging**
