### PR TITLE
Feat(i18n Translations): Addition of Multiple Languages

### PR DESCRIPTION
**Pull request by onedionys**
Hi Team,

I just added some languages to this PR that might be useful to use in the Oss App. Here is the list of languages that I have added:

* Arabic
* Azerbaijani (Azerbaijani Turkish)
* Bangla (Bengali / Bangladeshi)
* Basque
* Catalan
* Mongolian

Please check the languages that I have added first. And if there is no problem, you can merge this PR.

Thank you!

### CODE REVIEW

**Comment by onedionys** [comment]
Hi @getneil. Can you please help me to review and kindly advise if there is anything I need to follow up on?

Thank you very much

**Comment by onedionys** [comment]
I have finished the latest conflict, please check again.

**Comment by onedionys** [comment]
Hi @getneil, can you take a look at this Pull Request? I'm afraid my Pull Request is drowning because of the amount of Pull Request spam that someone is doing.

**Comment by onedionys** [comment]
Isn't there an update? @getneil

**Review by getneil — APPROVED** [review]

**Comment by getneil** [comment]
thanks @onedionys

**Comment by onedionys** [comment]
You're welcome. Thank you too @getneil. Have a nice day 😄

**Pull request merged**
