### PR TITLE
update gitignore

### PR DESCRIPTION
**Pull request by Gnayt**
Saw some typing error in the gitignore and wanna change it, also added package-lock.json to clean a bit the project since you need to install it before hand.

### CODE REVIEW

**Comment by mxcl** [comment]
Oh I thought the opposite. We definitely want `package-lock.json` committed. Removing it means different dependencies to our intention may be installed in CI/CD, locally and across teams/contributors which is a potential source of issues as well as potentially a security situation.

**Comment by Gnayt** [comment]
But the package-lock.json is essentially builded from package.json no ? I mean i thought it was the result of package.json. I will change it but didn't the package.json enough in this case ?

**Comment by mxcl** [comment]
The `package.json` represents ranges of applicable versions, eg. ^3 means 3.x. The lock file pins to specific versions.

I recommend reading up on this if you are confused. It is good practice to commit your lockfile, otherwise you are opening yourself up to a myriad of obscure bugs and issues between different build environments.

**Comment by mxcl** [comment]
diff still deletes the lockfile. Closing. The PR is a typo correction and has already occupied more of my time than it deserves.

**Pull request closed without merging**
