### PR TITLE
Create lv.json

### PR DESCRIPTION
**Pull request by edgars888**

### CODE REVIEW

**Comment by edgars888** [comment]
Hello 
all done please check

**Review by edgars888 — COMMENTED** [review]
hello

**Comment by getneil** [comment]
@edgars888 please also update the file `svelte/src/libs/translations/index.ts` to link the lv.json correctly

**Comment by edgars888** [comment]
Hello boss

**Comment by getneil** [comment]
refer to https://github.com/pkgxdev/ossapp/pull/831

**Pull request closed without merging**
