### PR TITLE
Estonian language again

### PR DESCRIPTION
**Pull request by nondevspell**
I have deleted my last rep and did it again maybe here will be not conflicts

### CODE REVIEW

**Comment by nondevspell** [comment]
why its not merged?

**Comment by getneil** [comment]
its failing lint or formatting. just need to run `xc format` then commit and push that to this pr and it should be ok.

**Comment by nondevspell** [comment]
can explain it more for me how I can run this format in my rep

**Comment by DavidKorystov** [comment]
> can explain it more for me how I can run this format in my rep

Clone a fork of your repository locally on your PC. Git & Nodejs should be installed beforehand. Install dependencies and run the command `npm run format`. Then push the changes to your repository on github.

**Comment by nondevspell** [comment]
image this?

**Comment by jhheider** [comment]
you need to `npm i` first to install the modules.

**Comment by nondevspell** [comment]
image
done

**Comment by getneil** [comment]
> image done

you need to stage, commit, and push it.

**Comment by DavidKorystov** [comment]
> image done

then `git add .`,
`git commit -m format-file`,
`git push -u origin main`

**Comment by getneil** [comment]
> > > image done
> > 
> > 
> > then `git add .`, `git commit -m "name-of-commit"`, `git push -u origin main`
> 
> im done? is that correct?

the package-lock.json is not necessary

**Pull request closed without merging**
