### PR TITLE
Create cz.json

### PR DESCRIPTION
**Pull request by Cornishon1**

### CODE REVIEW

**Comment by getneil** [comment]
@Cornishon1 please import it also in the svelte/src/libs/translations/index.ts after pl. thanks

and thank you for your contribution.

**Comment by Cornishon1** [comment]
imported, thanks.

**Comment by getneil** [comment]
@Cornishon1 can you push your commit for the import its not appearing in the files changed.

**Comment by Cornishon1** [comment]
okay, can i get contributor role in discord?

**Comment by mfts** [comment]
> okay, can i get contributor role in discord?

@Cornishon1 the contributor role will be assigned once the PR is merged. Please send me your Discord handle to assigned the role properly.

**Comment by Cornishon1** [comment]
Cornishon | Sui Global#8327, thanks

**Comment by Cornishon1** [comment]
> @Cornishon1 please import it also in the svelte/src/libs/translations/index.ts after pl. thanks
> 
> and thank you for your contribution.

I can just add it as the last one in the list, since Polish is not yet in the main branch, it is not available to you

**Comment by getneil** [comment]
@Cornishon1 can you address the conflict thanks.

**Pull request merged**
