### PR TITLE
Add Italian language 

### PR DESCRIPTION
**Pull request by 0xsingular**

### CODE REVIEW

**Review by getneil — APPROVED** [review]

**Comment by getneil** [comment]
thanks @0xsingular

**Comment by 0xsingular** [comment]
Hi, Neil could I get access to the contributors channel on discord to communicate and engage with the ideas developed there.

**Comment by getneil** [comment]
@mfts please add @0xsingular thanks

**Comment by 0xsingular** [comment]
Hi @mfts, any updates?
P.S. Sorry to bother you with this.

**Comment by mfts** [comment]
@getneil @mxcl i'm not longer in charge. I'm not sure who is responsible for it now.

**Comment by 0xsingular** [comment]
It’s okay, thanks for the reply.
And sorry again for bothering you!

**Comment by 0xsingular** [comment]
@getneil I can be in charge for this, on a volunteer basis, moderating/helping the community, assigning roles and XPs for activities on GitHub/Twitter.
Anyway at the moment due to my work most of the time I read and write, being all the time on GitHub/twitter (aka X)/ telegram and Ethereum.
It would be a pleasure for me to get involved and contribute more to the tea protocol.

**Comment by 0xsingular** [comment]
Thank you! @xercesblu3 I DM'd you on discord.

**Pull request merged**
