### PR TITLE
Обновить index.ts

### PR DESCRIPTION
**Pull request by adam50200**
Did I do the right thing?

### CODE REVIEW

**Comment by mxcl** [comment]
@getneil ?

**Comment by jhheider** [comment]
i don't see an `az.json` in [translations](https://github.com/pkgxdev/ossapp/tree/main/svelte/src/libs/translations/languages); that would need to be added with appropriate content, i would think.

**Comment by jhheider** [comment]
@adam50200 it looks like you'll need a few more changes, like [this](https://github.com/pkgxdev/ossapp/pull/844/files)

**Comment by getneil** [comment]
@adam50200 please add the json file for the translation.

**Comment by adam50200** [comment]
> i don't see an `az.json` in [translations](https://github.com/pkgxdev/ossapp/tree/main/svelte/src/libs/translations/languages); that would need to be added with appropriate content, i would think.

This one?
https://github.com/pkgxdev/ossapp/pull/832/files

**Comment by adam50200** [comment]
I'm confused, my head already hurts, I don't understand

**Comment by jhheider** [comment]
This and the other should be a single pull request.

**Comment by getneil** [comment]
no updates.

**Pull request closed without merging**
