### PR TITLE
latvian i18n

### PR DESCRIPTION
**Pull request by getneil**

### CODE REVIEW

**Comment by getneil** [comment]
@edgars888 this should be it.

**Comment by edgars888** [comment]
Thank you so much for helping me.

**Comment by edgars888** [comment]
Good evening, was wondering if I will not get HP points for this assignment and the Contributor role?

**Comment by getneil** [comment]
@mfts he did try to make a pr, translation was provided by him.

**Comment by mfts** [comment]
@edgars888 will add it rn

**Comment by edgars888** [comment]
Thanks a lot guys , you guys are really cool I'm starting to learn it's going hard but all little by little . more thanks again

**Pull request merged**
