### PR TITLE
french-translation

### PR DESCRIPTION
**Pull request by DavidKorystov**

### CODE REVIEW

**Comment by DavidKorystov** [comment]
If you are satisfied with this pull request, you can accept it and close this pull request. https://github.com/pkgxdev/ossapp/pull/837

**Review by getneil — APPROVED** [review]
thanks

**Comment by getneil** [comment]
@DavidKorystov thanks. please fix the conflicts.

**Comment by DavidKorystov** [comment]
@getneil done

**Comment by getneil** [comment]
@Xercesblu3 please check.

**Pull request merged**
