### PR TITLE
Translation to french 

### PR DESCRIPTION
**Pull request by DavidKorystov**

### CODE REVIEW

**Comment by getneil** [comment]
thank @DavidKorystov

**Comment by getneil** [comment]
@DavidKorystov lint is failing please fix thanks

**Comment by DavidKorystov** [comment]
.python-version & install-pyenv-win.ps1 Should these files be deleted?
@getneil

**Comment by DavidKorystov** [comment]
If these new files are not needed in this pull request, close this pull request and confirm the merge of this pull request. https://github.com/pkgxdev/ossapp/pull/841

**Pull request closed without merging**
