### PR TITLE
Vietnamese (vi)

### PR DESCRIPTION
**Pull request by berllx**
Vietnamese translation

### CODE REVIEW

**Comment by getneil** [comment]
@berllx  please fix conflict. sorry as i merge other prs from other contributors i just approve/merge those that addresses their issue the earliest.

**Comment by berllx** [comment]
@getneil I made the necessary changes

**Comment by getneil** [comment]
lint is failing please fix

**Comment by berllx** [comment]
@getneil sir conflict resolved

**Comment by berllx** [comment]
It’s a queue here, hope Vietnamese is next

**Review by getneil — APPROVED** [review]

**Pull request merged**
