### PR TITLE
Create edgars888latvia

### PR DESCRIPTION
**Pull request by edgars888**

### CODE REVIEW

**Comment by edgars888** [comment]
Hello

**Comment by getneil** [comment]
@edgars888 can you also import this on `svelte/src/libs/translations/index.ts` thanks

**Comment by edgars888** [comment]
Good day I can't figure out what I need to do here, as I understand you didn't accept my work.

**Comment by getneil** [comment]
@edgars888 

2 changes needs to be done

- [ ] proper language name for the json file, i assume `lv` is for latvia?
- [ ] checkout `svelte/src/libs/translations/index.ts` to see how to import `lv.json` to it.

**Comment by edgars888** [comment]
2 changes needs to be done

 proper language name for the json file, i assume lv is for latvia?
 checkout svelte/src/libs/translations/index.ts to see how to import lv.json to it.

Hello, we have made these two changes.
We have created a file en.json and
svelte/src/libs/translations/index.ts has been changed
import lv from "./languages/lv.json";
and 
const languages = [en, zh, de, ru, uk, ptbr, pl, cz, lv];

is there anything else to do?

**Comment by edgars888** [comment]
Good evening, I did the right thing. You looked at it.

**Comment by edgars888** [comment]
It's my first time doing it, I'm curious and I want it to work.

**Comment by getneil** [comment]
@edgars888 i think you have changed it in your local? but you need to stage and commit it, then push to update this pull-request.

**Comment by edgars888** [comment]
I think make update, can you pls check?

**Comment by getneil** [comment]
@edgars888 please do all updates in one pull-request. did you cloned this repository in your local? i have a feeling you are just directly editing online

**Comment by getneil** [comment]
changed to https://github.com/pkgxdev/ossapp/pull/831

**Pull request closed without merging**
