### PR TITLE
Finnish translation 

### PR DESCRIPTION
**Pull request by sarahjson**
Hi, I did the translation in Finnish, in my language 'Starstruck' has no translation, but we use this word as English meaning and writing.

### CODE REVIEW

**Comment by getneil** [comment]
@sarahjson please fix conflicts thanks

**Comment by sarahjson** [comment]
Sorry sir, what conflicts?

**Comment by DavidKorystov** [comment]
> Sorry sir, what conflicts?

merge confilcts 
Знімок екрана 2024-01-19 173654

**Comment by sarahjson** [comment]
@getneil I resolved the conflicts

**Comment by getneil** [comment]
@sarahjson please fix conflict again. sorry as i merge other prs from other contributors i just approve/merge those that addresses their issue the earliest.

**Comment by sarahjson** [comment]
@getneil Done

**Comment by getneil** [comment]
@sarahjson pleas fix the lint. `$ xc format` would probably do it.

**Comment by getneil** [comment]
lint is failing please fix

**Comment by sarahjson** [comment]
@getneil All checks have passed

**Review by getneil — APPROVED** [review]

**Pull request merged**
