### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by edgars888**

### CODE REVIEW

**Comment by getneil** [comment]
@edgars888 it did not. 

check this out the file changes should be together in the same pr. https://github.com/pkgxdev/ossapp/pull/805/files

**Comment by edgars888** [comment]
Good morning sir

**Comment by edgars888** [comment]
i think im done

**Comment by edgars888** [comment]
could you check when you have time?

**Comment by getneil** [comment]
> could you check when you have time?

Check the comment I made above. Thanks

**Comment by getneil** [comment]
refer to https://github.com/pkgxdev/ossapp/pull/831

**Pull request closed without merging**
